---
- name: play
  hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: play
      copy:
        src: /home/ansible/project.war
        dest: /root/apache-tomcat-9.0.89/webapps/pro.war
